#!/usr/bin/env bash
# ==============================================================================
# WALLPAPER SWITCHER + DYNAMIC COLOR GENERATOR
# Integrates Wallust for automatic palette generation on wallpaper change.
# Falls back to static Tokyo Night Synth palette if wallust is not installed.
# Usage: wallpaper.sh [wallpaper_filename]
# ==============================================================================

WALLPAPER_DIR="${HOME}/.config/appearance/wallpapers"
COLORS_OUT="${HOME}/.config/appearance/colors.conf"
WALLPAPER_SYMLINK="${HOME}/.config/appearance/wallpaper_active"

WALLPAPER="${1:-}"

# --- Resolve wallpaper path ---
if [ -n "$WALLPAPER" ]; then
    if [ -f "${WALLPAPER_DIR}/${WALLPAPER}" ]; then
        WALLPAPER_PATH="${WALLPAPER_DIR}/${WALLPAPER}"
    elif [ -f "$WALLPAPER" ]; then
        WALLPAPER_PATH="$WALLPAPER"
    else
        echo "[!] Wallpaper not found: ${WALLPAPER}"
        echo "[!] Available wallpapers:"
        ls "${WALLPAPER_DIR}/"
        exit 1
    fi
else
    if [ -L "$WALLPAPER_SYMLINK" ] && [ -f "$WALLPAPER_SYMLINK" ]; then
        WALLPAPER_PATH="$(readlink -f "$WALLPAPER_SYMLINK")"
    else
        WALLPAPER_PATH="${WALLPAPER_DIR}/tokyo-lofi-cityscape.jpg"
    fi
fi

echo "[*] Setting wallpaper: $(basename "${WALLPAPER_PATH}")"

# --- Update active symlink ---
ln -sf "$WALLPAPER_PATH" "$WALLPAPER_SYMLINK"

# --- Set wallpaper via swww or hyprpaper ---
if command -v swww >/dev/null 2>&1; then
    swww init 2>/dev/null || true
    swww img "$WALLPAPER_PATH" \
        --transition-type grow \
        --transition-pos 0.85,0.95 \
        --transition-step 90 \
        --transition-fps 60
elif command -v hyprctl >/dev/null 2>&1; then
    hyprctl hyprpaper unload all 2>/dev/null || true
    hyprctl hyprpaper preload "$WALLPAPER_PATH" 2>/dev/null || true
    hyprctl hyprpaper wallpaper ",$WALLPAPER_PATH" 2>/dev/null || true
fi

echo "[✓] Wallpaper set."

# --- Dynamic Color Generation via Wallust ---
if command -v wallust >/dev/null 2>&1; then
    echo "[*] Running Wallust for dynamic palette generation..."
    wallust run "$WALLPAPER_PATH"

    WALLUST_COLORS="${HOME}/.config/wallust/colors.sh"
    if [ -f "$WALLUST_COLORS" ] && [ -r "$WALLUST_COLORS" ]; then
        # shellcheck source=/dev/null
        source "$WALLUST_COLORS"

        cat > "$COLORS_OUT" <<EOF
# AUTO-GENERATED by wallust via wallpaper.sh — do not edit manually.
# Wallpaper: $(basename "${WALLPAPER_PATH}")
# To use static Tokyo Night Synth colors, remove wallust from PATH.

\$bg = rgb(${wallust_color0//#/})
\$bg_hex = ${wallust_color0//#/}
\$surface = rgba(${wallust_color8//#/}e6)
\$surface_hex = ${wallust_color8//#/}
\$accent_pink = rgb(${wallust_color1//#/})
\$accent_pink_hex = ${wallust_color1//#/}
\$accent_cyan = rgb(${wallust_color4//#/})
\$accent_cyan_hex = ${wallust_color4//#/}
\$fg = rgb(${wallust_color15//#/})
\$fg_hex = ${wallust_color15//#/}
\$border_active = rgb(${wallust_color1//#/})
\$border_inactive = rgb(${wallust_color8//#/})
\$shadow_color = rgba(${wallust_color0//#/}aa)
EOF
        echo "[✓] Hyprland colors.conf updated from Wallust palette."
    fi

    # Reload Hyprland to apply new border colors
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl reload 2>/dev/null && echo "[✓] Hyprland reloaded."
    fi

    # Reload Waybar — fixed operator precedence
    if ! pkill -SIGUSR2 waybar 2>/dev/null; then
        pkill -x waybar 2>/dev/null || true
        sleep 0.5
        waybar -c ~/.config/waybar/config-top.jsonc -s ~/.config/waybar/style.css &
        waybar -c ~/.config/waybar/config-dock.jsonc -s ~/.config/waybar/style.css &
    fi
    echo "[✓] Waybar reloaded."

else
    echo "[!] wallust not found — keeping static Tokyo Night Synth palette."
    echo "[!] Install: sudo pacman -S wallust  (or: yay -S wallust-git)"
fi

echo "[✓] Wallpaper switch complete. Opacity rules preserved."
